/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.eam.edu.ingesoft.pa.avanzada.gui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.naming.NamingException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import co.eam.edu.ingesoft.pa.avanzada.controladoresGUI.ControladorBancoPrincipal;
import co.edu.eam.ingesoft.pa.negocio.excepciones.ExcepcionNegocio;
import entidades.Cliente;
import entidades.ConsumoTarjetaCredito;
import entidades.CuentaAhorros;
import entidades.Franquicia;
import entidades.PagoCunsumoTarCredito;
import entidades.TarjetaCredito;
import entidades.Transaccion;
import enumeraciones.TipoDocumento;

/**
 *
 * @author Alejandro Ortega
 */
public class BancoPrincipal extends javax.swing.JFrame {

	private ControladorBancoPrincipal controlador;

	/**
	 * Creates new form BancoPrincipal
	 */
	public BancoPrincipal() {
		initComponents();
		try {
			jTFCvc.setVisible(false);
			jTFInteres.setVisible(false);
			jCBFranquicia.setVisible(false);
			jDateFechaExpiracion.setVisible(false);
			jLCvc.setVisible(false);
			jLInteres.setVisible(false);
			jLFranquicia.setVisible(false);
			jLFechaExpiracion.setVisible(false);
			jLIngreseValorPago.setVisible(false);
			jTFIngreseValorPago.setVisible(false);
			jTFNumeroCuentaOrigen.setVisible(false);
			jLNumeroCuentaTransaccionOrigen.setVisible(false);
			controlador = new ControladorBancoPrincipal();
			listarCombo(jCBFranquicia);
			jCBTipoId.addItem("Seleccione una opción");
			jCBTipoId.addItem(TipoDocumento.CC);
			jCBTipoId.addItem(TipoDocumento.CE);
			jCBTipoId.addItem(TipoDocumento.PAS);
			jCBTipoId.addItem(TipoDocumento.TI);

			jCBIdClienteProducto.addItem("Seleccione una opción");
			jCBIdClienteProducto.addItem(TipoDocumento.CC);
			jCBIdClienteProducto.addItem(TipoDocumento.CE);
			jCBIdClienteProducto.addItem(TipoDocumento.PAS);
			jCBIdClienteProducto.addItem(TipoDocumento.TI);

		} catch (NamingException e) {

			e.printStackTrace();
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTPPrincipal = new javax.swing.JTabbedPane();
        jPCliente = new javax.swing.JPanel();
        jLTipo = new javax.swing.JLabel();
        jCBTipoId = new javax.swing.JComboBox();
        jLId = new javax.swing.JLabel();
        jTFId = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jBGuardarCliente = new javax.swing.JButton();
        jBBuscarCliente = new javax.swing.JButton();
        jPProducto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCBTipoProducto = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTFNumeroPro = new javax.swing.JTextField();
        jTFIdCLienteProducto = new javax.swing.JTextField();
        jCBIdClienteProducto = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLIdClienteProducto = new javax.swing.JLabel();
        jTFSaldo = new javax.swing.JTextField();
        jLSaldo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLCvc = new javax.swing.JLabel();
        jTFCvc = new javax.swing.JTextField();
        jLFechaExpiracion = new javax.swing.JLabel();
        jDateFechaExpiracion = new com.toedter.calendar.JDateChooser();
        jLFranquicia = new javax.swing.JLabel();
        jCBFranquicia = new javax.swing.JComboBox();
        jBCrearProducto = new javax.swing.JButton();
        jLInteres = new javax.swing.JLabel();
        jTFInteres = new javax.swing.JTextField();
        jBBuscarProducto = new javax.swing.JButton();
        jPOperacion = new javax.swing.JPanel();
        jlTipoOperacion = new javax.swing.JLabel();
        jCBTipoTransaccion = new javax.swing.JComboBox();
        jLCantidadOperacion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTFCantidadTransaccion = new javax.swing.JTextField();
        jLNumeroCuentaTransaccion = new javax.swing.JLabel();
        jTFNumeroCuentaTransaccion = new javax.swing.JTextField();
        jBGuardarTransaccion = new javax.swing.JButton();
        jLNumeroCuentaTransaccionOrigen = new javax.swing.JLabel();
        jTFNumeroCuentaOrigen = new javax.swing.JTextField();
        jPConsumo = new javax.swing.JPanel();
        jLValorTotalConsumo = new javax.swing.JLabel();
        jTFValorTotalConsumo = new javax.swing.JTextField();
        jInteresConsumo = new javax.swing.JLabel();
        jTFInteresConsumo = new javax.swing.JTextField();
        jLNumeroCuotasConsumo = new javax.swing.JLabel();
        jLValorPorPagarConsumo = new javax.swing.JLabel();
        jLTarjetaCreditoConsumo = new javax.swing.JLabel();
        jTFValorXPagarConsumo = new javax.swing.JTextField();
        jTFTarjetaCreditoConsumo = new javax.swing.JTextField();
        jCBCuotasConsumo = new javax.swing.JComboBox();
        jLPag = new javax.swing.JLabel();
        jLPagadoBoolean = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBGuardarConsumo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jCBTipoConsumo = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLValorPagarPago = new javax.swing.JLabel();
        jLAbonoCapital = new javax.swing.JLabel();
        jLAbonoInteres = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTFValorPagarPago = new javax.swing.JTextField();
        jTFAbonoCapital = new javax.swing.JTextField();
        jTFAbonoInteres = new javax.swing.JTextField();
        jtfNumeroTCPago = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCBComoElPago = new javax.swing.JComboBox();
        jBGenerarPago = new javax.swing.JButton();
        jBRealizarPago = new javax.swing.JButton();
        jLIngreseValorPago = new javax.swing.JLabel();
        jTFIngreseValorPago = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Banco CONCORDIA");

        jTPPrincipal.setFont(new java.awt.Font("Simplified Arabic", 1, 14)); // NOI18N

        jLTipo.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLTipo.setText("TIPO DE IDENTIFICACIÓN:");

        jCBTipoId.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jLId.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLId.setText("IDENTIFICACIÓN:");

        jTFId.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jLNombre.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLNombre.setText("NOMBRE:");

        jLApellido.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLApellido.setText("APELLIDO:");

        jTFNombre.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jTFApellido.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jBGuardarCliente.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jBGuardarCliente.setText("GUARDAR CLIENTE");
        jBGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarClienteActionPerformed(evt);
            }
        });

        jBBuscarCliente.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jBBuscarCliente.setText("BUSCAR CLIENTE");
        jBBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPClienteLayout = new javax.swing.GroupLayout(jPCliente);
        jPCliente.setLayout(jPClienteLayout);
        jPClienteLayout.setHorizontalGroup(
            jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTipo)
                    .addComponent(jLId)
                    .addComponent(jLNombre)
                    .addComponent(jLApellido))
                .addGap(18, 18, 18)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jCBTipoId, 0, 201, Short.MAX_VALUE)
                    .addComponent(jTFId)
                    .addComponent(jTFNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBGuardarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );
        jPClienteLayout.setVerticalGroup(
            jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClienteLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipo)
                    .addComponent(jCBTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLId)
                    .addComponent(jTFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGuardarCliente))
                .addGap(29, 29, 29)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarCliente))
                .addGap(32, 32, 32)
                .addGroup(jPClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(jTFApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        jTPPrincipal.addTab("Cliente", jPCliente);

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLabel6.setText("TIPO DE PRODUCTO:");

        jCBTipoProducto.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jCBTipoProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opción:", "Cuenta de ahorros", "Tarjeta de credito" }));
        jCBTipoProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoProductoItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLabel7.setText("NUMERO:");

        jTFNumeroPro.setEditable(false);
        jTFNumeroPro.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jTFIdCLienteProducto.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jCBIdClienteProducto.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLabel8.setText("TIPO DE IDENTIFICACIÓN:");

        jLIdClienteProducto.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLIdClienteProducto.setText("IDENTIFICACIÓN:");

        jTFSaldo.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jLSaldo.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLSaldo.setText("SALDO");

        jLabel11.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jLabel11.setText("$");

        jLCvc.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLCvc.setText("CVC*");

        jTFCvc.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jTFCvc.setEnabled(false);

        jLFechaExpiracion.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLFechaExpiracion.setText("FECHA EXPIRACIÓN:");

        jDateFechaExpiracion.setEnabled(false);

        jLFranquicia.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLFranquicia.setText("FRANQUICIA:");

        jCBFranquicia.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jCBFranquicia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBCrearProducto.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jBCrearProducto.setText("CREAR PRODUCTO");
        jBCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearProductoActionPerformed(evt);
            }
        });

        jLInteres.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLInteres.setText("INTERES DE AHORRO:");

        jTFInteres.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jBBuscarProducto.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jBBuscarProducto.setText("BUSCAR PRODUCTO");
        jBBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPProductoLayout = new javax.swing.GroupLayout(jPProducto);
        jPProducto.setLayout(jPProductoLayout);
        jPProductoLayout.setHorizontalGroup(
            jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProductoLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLFranquicia)
                            .addComponent(jLFechaExpiracion))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPProductoLayout.createSequentialGroup()
                        .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLInteres)
                                .addGroup(jPProductoLayout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jBCrearProducto))
                                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLSaldo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLIdClienteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLCvc, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPProductoLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jBBuscarProducto)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProductoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFNumeroPro, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBIdClienteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFIdCLienteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFCvc, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))))))
        );
        jPProductoLayout.setVerticalGroup(
            jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProductoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCBTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNumeroPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCBIdClienteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdClienteProducto)
                    .addComponent(jTFIdCLienteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jLSaldo))
                .addGap(18, 18, 18)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLInteres)
                    .addComponent(jTFInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLFechaExpiracion)
                    .addComponent(jDateFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFranquicia)
                    .addComponent(jCBFranquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCvc)
                    .addComponent(jTFCvc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrearProducto)
                    .addComponent(jBBuscarProducto))
                .addContainerGap())
        );

        jTPPrincipal.addTab("Producto", jPProducto);

        jlTipoOperacion.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jlTipoOperacion.setText("TIPO:");

        jCBTipoTransaccion.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jCBTipoTransaccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una transacción:", "Consignación", "Retiro", "Transferencia" }));
        jCBTipoTransaccion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoTransaccionItemStateChanged(evt);
            }
        });

        jLCantidadOperacion.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLCantidadOperacion.setText("CANTIDAD:");

        jLabel12.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jLabel12.setText("$");

        jTFCantidadTransaccion.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jLNumeroCuentaTransaccion.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLNumeroCuentaTransaccion.setText("NUMERO DE CUENTA DE AHORROS:");

        jTFNumeroCuentaTransaccion.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jBGuardarTransaccion.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jBGuardarTransaccion.setText("ACEPTAR TRANSACCIÓN");
        jBGuardarTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarTransaccionActionPerformed(evt);
            }
        });

        jLNumeroCuentaTransaccionOrigen.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLNumeroCuentaTransaccionOrigen.setText(" CUENTA DE AHORROS ORIGEN:");

        jTFNumeroCuentaOrigen.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPOperacionLayout = new javax.swing.GroupLayout(jPOperacion);
        jPOperacion.setLayout(jPOperacionLayout);
        jPOperacionLayout.setHorizontalGroup(
            jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacionLayout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jBGuardarTransaccion)
                .addContainerGap(316, Short.MAX_VALUE))
            .addGroup(jPOperacionLayout.createSequentialGroup()
                .addGroup(jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPOperacionLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLCantidadOperacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCantidadTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPOperacionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlTipoOperacion)
                                .addComponent(jLNumeroCuentaTransaccionOrigen))
                            .addComponent(jLNumeroCuentaTransaccion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPOperacionLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBTipoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFNumeroCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOperacionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNumeroCuentaTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(131, 131, 131))
        );
        jPOperacionLayout.setVerticalGroup(
            jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOperacionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPOperacionLayout.createSequentialGroup()
                        .addGroup(jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTipoOperacion)
                            .addComponent(jCBTipoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLCantidadOperacion)))
                    .addComponent(jTFCantidadTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNumeroCuentaTransaccion)
                    .addComponent(jTFNumeroCuentaTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumeroCuentaTransaccionOrigen)
                    .addComponent(jTFNumeroCuentaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jBGuardarTransaccion)
                .addGap(27, 27, 27))
        );

        jTPPrincipal.addTab("Operaciones de la cuenta", jPOperacion);

        jLValorTotalConsumo.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLValorTotalConsumo.setText("VALOR TOTAL DEL CONSUMO:");

        jTFValorTotalConsumo.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jTFValorTotalConsumo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFValorTotalConsumoKeyReleased(evt);
            }
        });

        jInteresConsumo.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jInteresConsumo.setText("INTERES:");

        jTFInteresConsumo.setEditable(false);
        jTFInteresConsumo.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jTFInteresConsumo.setText("3.6");

        jLNumeroCuotasConsumo.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLNumeroCuotasConsumo.setText("NUMERO DE CUOTAS:");

        jLValorPorPagarConsumo.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLValorPorPagarConsumo.setText("VALOR POR PAGAR:");

        jLTarjetaCreditoConsumo.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLTarjetaCreditoConsumo.setText("TARJETA DE CREDITO:");

        jTFValorXPagarConsumo.setEditable(false);
        jTFValorXPagarConsumo.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jTFTarjetaCreditoConsumo.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jCBCuotasConsumo.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jCBCuotasConsumo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione numero de cuotas:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        jLPag.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLPag.setText("PAGADO:");

        jLPagadoBoolean.setText("NO PAGO");

        jLabel2.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jLabel2.setText("$");

        jLabel3.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jLabel3.setText("$");

        jBGuardarConsumo.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jBGuardarConsumo.setText("GUARDAR CONSUMO");
        jBGuardarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarConsumoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLabel4.setText("TIPO:");

        jCBTipoConsumo.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jCBTipoConsumo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un tipo:", "Avance", "Consumo" }));
        jCBTipoConsumo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBTipoConsumoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPConsumoLayout = new javax.swing.GroupLayout(jPConsumo);
        jPConsumo.setLayout(jPConsumoLayout);
        jPConsumoLayout.setHorizontalGroup(
            jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsumoLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPConsumoLayout.createSequentialGroup()
                        .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jInteresConsumo)
                            .addComponent(jLNumeroCuotasConsumo)
                            .addComponent(jLTarjetaCreditoConsumo)
                            .addComponent(jLValorPorPagarConsumo)
                            .addComponent(jLPag)
                            .addComponent(jLValorTotalConsumo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPConsumoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(299, 299, 299)))
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFValorTotalConsumo)
                    .addComponent(jTFInteresConsumo)
                    .addComponent(jTFValorXPagarConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(jCBCuotasConsumo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFTarjetaCreditoConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(jLPagadoBoolean, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBTipoConsumo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPConsumoLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jBGuardarConsumo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPConsumoLayout.setVerticalGroup(
            jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPConsumoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCBTipoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLValorTotalConsumo)
                    .addComponent(jTFValorTotalConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInteresConsumo)
                    .addComponent(jTFInteresConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumeroCuotasConsumo)
                    .addComponent(jCBCuotasConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLValorPorPagarConsumo)
                    .addComponent(jTFValorXPagarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTarjetaCreditoConsumo)
                    .addComponent(jTFTarjetaCreditoConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPag)
                    .addComponent(jLPagadoBoolean))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBGuardarConsumo)
                .addGap(23, 23, 23))
        );

        jTPPrincipal.addTab("Consumo de tarjeta de credito", jPConsumo);

        jLValorPagarPago.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLValorPagarPago.setText("VALOR A PAGAR:");

        jLAbonoCapital.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLAbonoCapital.setText("ABONO A CAPITAL:");

        jLAbonoInteres.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLAbonoInteres.setText("ABONO A INTERES:");

        jLabel13.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLabel13.setText("NUMERO DE TARJETA DE CREDITO:");

        jTFValorPagarPago.setEditable(false);
        jTFValorPagarPago.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jTFAbonoCapital.setEditable(false);
        jTFAbonoCapital.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jTFAbonoInteres.setEditable(false);
        jTFAbonoInteres.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jtfNumeroTCPago.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLabel14.setText("¿COMO DESEA REALIZAR EL PAGO?");

        jCBComoElPago.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N
        jCBComoElPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione como desea realizar el pago:", "Pago definido", "Ingresar valor" }));
        jCBComoElPago.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBComoElPagoItemStateChanged(evt);
            }
        });

        jBGenerarPago.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jBGenerarPago.setText("GENERAR PAGO");
        jBGenerarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerarPagoActionPerformed(evt);
            }
        });

        jBRealizarPago.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jBRealizarPago.setText("REALIZAR PAGO");
        jBRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRealizarPagoActionPerformed(evt);
            }
        });

        jLIngreseValorPago.setFont(new java.awt.Font("Simplified Arabic", 1, 12)); // NOI18N
        jLIngreseValorPago.setText("INGRESE VALOR A PAGAR:");

        jTFIngreseValorPago.setFont(new java.awt.Font("Simplified Arabic", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLAbonoInteres)
                            .addComponent(jLIngreseValorPago)
                            .addComponent(jLValorPagarPago)
                            .addComponent(jLAbonoCapital))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFAbonoCapital, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFAbonoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBComoElPago, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfNumeroTCPago, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBGenerarPago))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTFValorPagarPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                .addComponent(jTFIngreseValorPago, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jBRealizarPago)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jCBComoElPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfNumeroTCPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGenerarPago))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIngreseValorPago)
                    .addComponent(jTFIngreseValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLValorPagarPago)
                    .addComponent(jTFValorPagarPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAbonoCapital)
                    .addComponent(jTFAbonoCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAbonoInteres)
                    .addComponent(jTFAbonoInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jBRealizarPago)
                .addGap(46, 46, 46))
        );

        jTPPrincipal.addTab("Pago del consumo", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTPPrincipal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTPPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jCBTipoTransaccionItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jCBTipoTransaccionItemStateChanged
		// TODO add your handling code here:
		if (jCBTipoTransaccion.getSelectedIndex() == 3) {
			jTFNumeroCuentaOrigen.setVisible(true);
			jLNumeroCuentaTransaccionOrigen.setVisible(true);
		} else {
			jTFNumeroCuentaOrigen.setVisible(false);
			jLNumeroCuentaTransaccionOrigen.setVisible(false);
		}
	}// GEN-LAST:event_jCBTipoTransaccionItemStateChanged

	private void jCBComoElPagoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jCBComoElPagoItemStateChanged
		// TODO add your handling code here:
		if (jCBComoElPago.getSelectedIndex() == 0) {
			jLIngreseValorPago.setVisible(false);
			jTFIngreseValorPago.setVisible(false);

		} else if (jCBComoElPago.getSelectedIndex() == 1) {
			jLIngreseValorPago.setVisible(false);
			jTFIngreseValorPago.setVisible(false);
			// double valor = Double.parseDouble(jTFValorPagarPago.getText());
			// jTFIngreseValorPago.setText(valor+"");
		} else if (jCBComoElPago.getSelectedIndex() == 2) {
			jLIngreseValorPago.setVisible(true);
			jTFIngreseValorPago.setVisible(true);
		}
	}// GEN-LAST:event_jCBComoElPagoItemStateChanged

	private void jTFValorTotalConsumoKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTFValorTotalConsumoKeyReleased
		// TODO add your handling code here:
		jTFValorXPagarConsumo.setText(jTFValorTotalConsumo.getText());
	}// GEN-LAST:event_jTFValorTotalConsumoKeyReleased

	private void jBRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBRealizarPagoActionPerformed
		// TODO add your handling code here:
		try {
			if (jCBComoElPago.getSelectedIndex() == 0 || jtfNumeroTCPago.getText().isEmpty()
					|| jTFValorPagarPago.getText().isEmpty() || jTFAbonoCapital.getText().isEmpty()
					|| jTFAbonoInteres.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Llene todos los campos");
			} else {
				String tcnum = jtfNumeroTCPago.getText();
				TarjetaCredito tc = controlador.buscarTarjeta(tcnum);
				double valorPagar = controlador.calcularCuota(tc);
				double deudatotal = controlador.valorDeuda(tc);
				controlador.pagarCuota(valorPagar, tc, valorPagar, deudatotal);
				if (jTFValorPagarPago.getText().equals("0.0") || jTFAbonoCapital.getText().equals("0.0")) {
					JOptionPane.showMessageDialog(null, "No debe nada");
				} else {
					JOptionPane.showMessageDialog(null, "Pago realizado con exito");
					limpiarPago();
				}
			}
		} catch (ExcepcionNegocio e) {
			JOptionPane.showMessageDialog(null, e.getMessage());
			// TODO: handle exception
		}
	}// GEN-LAST:event_jBRealizarPagoActionPerformed

	private void jBGenerarPagoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBGenerarPagoActionPerformed
		// TODO add your handling code here:
		if (jCBComoElPago.getSelectedIndex() == 0 || jtfNumeroTCPago.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Llene todos los campos");
		} else if (jCBComoElPago.getSelectedIndex() == 1) {
			String tcnum = jtfNumeroTCPago.getText();
			TarjetaCredito tc = controlador.buscarTarjeta(tcnum);
			double valorPagar = controlador.calcularCuota(tc);
			double valorMostrarCapital = controlador.calcularCuotaSinInteres(tc);
			jTFValorPagarPago.setText(valorPagar + "");
			jTFAbonoCapital.setText(valorMostrarCapital + "");
			jTFAbonoInteres.setText(3.6 + "");
		} else {
			JOptionPane.showMessageDialog(null, "Este modo esta en matenimiento");
		}

	}// GEN-LAST:event_jBGenerarPagoActionPerformed

	private void jBGuardarConsumoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBGuardarConsumoActionPerformed
		// TODO add your handling code here:

		if (jCBTipoConsumo.getSelectedIndex() == 0 || jTFValorTotalConsumo.getText().isEmpty()
				|| jTFInteresConsumo.getText().isEmpty() || jCBCuotasConsumo.getSelectedIndex() == 0
				|| jTFValorXPagarConsumo.getText().isEmpty() || jTFTarjetaCreditoConsumo.getText().isEmpty()) {

			JOptionPane.showMessageDialog(null, "Ingrese todos los datos");

		} else {
			ConsumoTarjetaCredito consumo;

			double totalConsumo = Double.parseDouble(jTFValorTotalConsumo.getText());
			double interes = Double.parseDouble(jTFInteresConsumo.getText());
			int cuotas = Integer.parseInt((String) jCBCuotasConsumo.getSelectedItem());
			double valorPorPagar = Double.parseDouble(jTFValorXPagarConsumo.getText());
			String num = jTFTarjetaCreditoConsumo.getText();
			boolean pago = false;
			Date fechaConsumo = new Date();
			TarjetaCredito tc = controlador.buscarTarjeta(num);
			if (tc == null) {
				JOptionPane.showMessageDialog(null, "Esta tarjeta de credito no existe");
			} else {
				double cantidadTC = tc.getAmmount();
				if (totalConsumo <= cantidadTC) {
					double ammountFinal = cantidadTC - totalConsumo;
					TarjetaCredito tarj = new TarjetaCredito(tc.getNumber(), tc.getExpedition_date(), tc.getCliente(),
							tc.getCvc(), ammountFinal, tc.getExpirationDate(), tc.getFranchise());

					consumo = new ConsumoTarjetaCredito(0, fechaConsumo, cuotas, totalConsumo, interes, valorPorPagar,
							pago, tarj, cuotas);

					controlador.editarTC(tarj);
					controlador.GuardarConsumo(consumo);
					JOptionPane.showMessageDialog(null, "Consumo guardado");
					limpiarConsumo();
				} else {
					JOptionPane.showMessageDialog(null, "Su tarjeta de credito no cuenta con esta capacidad");
				}
			}
		}

	}// GEN-LAST:event_jBGuardarConsumoActionPerformed

	private void jCBTipoConsumoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jCBTipoConsumoItemStateChanged
		// TODO add your handling code here:
		if (jCBTipoConsumo.getSelectedItem() == "Avance") {
			jCBCuotasConsumo.setSelectedItem("24");
			jCBCuotasConsumo.setEnabled(false);
		} else if (jCBTipoConsumo.getSelectedItem() == "Consumo") {
			jCBCuotasConsumo.setEnabled(true);
			jCBCuotasConsumo.setSelectedIndex(0);
		}
	}// GEN-LAST:event_jCBTipoConsumoItemStateChanged

	private void jBGuardarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBGuardarTransaccionActionPerformed
		// TODO add your handling code here:
		try {
			if (jCBTipoTransaccion.getSelectedIndex() == 0 || jTFCantidadTransaccion.getText().isEmpty()
					 || jTFNumeroCuentaTransaccion.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Porfavor llene todos los campos");
			} else {
				String tipo = (String) jCBTipoTransaccion.getSelectedItem();
				double cantidad = Double.parseDouble(jTFCantidadTransaccion.getText());
				String numeroCuenta = jTFNumeroCuentaTransaccion.getText();
				CuentaAhorros cuenta = controlador.buscarCuentaAhorros(numeroCuenta);
				Date fechaTransaccion = new Date();
				String fuenteTr = "appMovil";
						// DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss
				// dd/MM/yyyy");
				if (cuenta != null) {

					boolean bandera = false;

					if (jCBTipoTransaccion.getSelectedIndex() == 1) {
						// consignacion
						bandera = controlador.consignacion(cuenta, cantidad, fechaTransaccion,fuenteTr, tipo);
					} else if (jCBTipoTransaccion.getSelectedIndex() == 2) {
						// retiro
						bandera = controlador.retiro(cuenta, cantidad, fechaTransaccion, fuenteTr, tipo);

					} else if (jCBTipoTransaccion.getSelectedIndex() == 3) {
						// transferencia
						//bandera = controlador.transferencia(cuenta, cantidad, fechaTransaccion, fuenteTr, tipo);
					try{
						String cuentaDest = jTFNumeroCuentaOrigen.getText();
						controlador.transferir(cuentaDest,numeroCuenta, cantidad);
						bandera = true;
					}catch(ExcepcionNegocio e){
						JOptionPane.showMessageDialog(null,e.getMessage());
					}
					}
					if (bandera) {
						JOptionPane.showMessageDialog(null,
								"Transacción realizada satisfactoriamente a la cuenta " + cuenta.getNumber() + ""
										+ " perteneciente a " + cuenta.getCliente().getName() + " "
										+ cuenta.getCliente().getLastName());
						limpiarCamposTransaccion();
					} else {
						JOptionPane.showMessageDialog(null, "No fue posible la transacción");
					}

				} else {
					JOptionPane.showMessageDialog(null, "Esta cuenta de ahorros no existe");
				}
			}

		} catch (ExcepcionNegocio e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_jBGuardarTransaccionActionPerformed

	private void jBBuscarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBBuscarTransaccionActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBBuscarTransaccionActionPerformed

	private void jCBTipoProductoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_jCBTipoProductoItemStateChanged
		// TODO add your handling code here:
		if (jCBTipoProducto.getSelectedIndex() == 1) {
			String num = controlador.generarCuentaAhorro();
			jTFNumeroPro.setText(num);
			jTFCvc.setVisible(false);
			jTFInteres.setVisible(true);
			jCBFranquicia.setVisible(false);
			jDateFechaExpiracion.setVisible(false);
			jLCvc.setVisible(false);
			jLInteres.setVisible(true);
			jLFranquicia.setVisible(false);
			jLFechaExpiracion.setVisible(false);

		} else if (jCBTipoProducto.getSelectedIndex() == 2) {
			Date expi = controlador.generarFechaExpiracion();
			String cvc = controlador.generarCVC();
			String num = controlador.generarTarjetaCredito();
			jTFNumeroPro.setText(num);
			jDateFechaExpiracion.setDate(expi);
			jTFCvc.setText(cvc);
			jTFCvc.setVisible(true);
			jTFInteres.setVisible(false);
			jCBFranquicia.setVisible(true);
			jDateFechaExpiracion.setVisible(true);
			jLCvc.setVisible(true);
			jLInteres.setVisible(false);
			jLFranquicia.setVisible(true);
			jLFechaExpiracion.setVisible(true);
		} else if (jCBTipoProducto.getSelectedIndex() == 0) {
			limpiarCamposProducto();
			jTFCvc.setVisible(false);
			jTFInteres.setVisible(false);
			jCBFranquicia.setVisible(false);
			jDateFechaExpiracion.setVisible(false);
			jLCvc.setVisible(false);
			jLInteres.setVisible(false);
			jLFranquicia.setVisible(false);
			jLFechaExpiracion.setVisible(false);
		}
	}// GEN-LAST:event_jCBTipoProductoItemStateChanged

	private void jBCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			if (jCBTipoProducto.getSelectedIndex() == 2) {
				if (jTFIdCLienteProducto.getText().isEmpty() || jTFSaldo.getText().isEmpty()
						|| jCBIdClienteProducto.getSelectedIndex() == 0 || jCBFranquicia.getSelectedIndex() == 0) {
					JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
				} else {
					TarjetaCredito tarjeta;

					String numero = jTFNumeroPro.getText();
					String cvc = jTFCvc.getText();
					Date fechaexpedicion = new Date();
					Date fechaExpiracion = jDateFechaExpiracion.getDate();
					double saldo = Double.parseDouble(jTFSaldo.getText());
					String cedula = jTFIdCLienteProducto.getText();
					TipoDocumento tipoCed = (TipoDocumento) jCBIdClienteProducto.getSelectedItem();
					String nombreFranquicia = (String) jCBFranquicia.getSelectedItem();
					Franquicia fra = controlador.buscarPorNombreFranquicia(nombreFranquicia);
					Cliente cli = controlador.buscarCliente(tipoCed, cedula);
					if (cli == null) {
						JOptionPane.showMessageDialog(null, "Este usuario no existe");
					} else {
						int verif = controlador.verificarCantidadTC(cli);
						int numVer = controlador.CantidadPro(cli);
						boolean verificacionPro = controlador.verificarCantidadPro(cli);
						System.out.println(verif);
						if (verif > 1) {
							JOptionPane.showMessageDialog(null, "Ya tiene 2 TARJETAS DE CREDITO");
						} else if (!verificacionPro) {
							JOptionPane.showMessageDialog(null, "Ya tiene 5 PRODUCTOS");
						} else {

							tarjeta = new TarjetaCredito(numero, fechaexpedicion, cli, cvc, saldo, fechaExpiracion,
									fra);

							controlador.crearTarjetaCredito(tarjeta);
							JOptionPane.showMessageDialog(null, "Tarjeta de credito creada y asignada a: "
									+ cli.getName() + " " + cli.getLastName());
							limpiarCamposProducto();
							limpiarTipoProducto();
						}
					}
				}

			} else if (jCBTipoProducto.getSelectedIndex() == 1) {
				if (jTFIdCLienteProducto.getText().isEmpty() || jTFSaldo.getText().isEmpty()
						|| jCBIdClienteProducto.getSelectedIndex() == 0 || jTFInteres.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Por favor ingrese todos los datos");
				} else {
					CuentaAhorros cuenta;

					String numero = jTFNumeroPro.getText();
					Date fechaexpedicion = new Date();
					double saldo = Double.parseDouble(jTFSaldo.getText());
					String cedula = jTFIdCLienteProducto.getText();
					TipoDocumento tipoCed = (TipoDocumento) jCBIdClienteProducto.getSelectedItem();
					double interes = Double.parseDouble(jTFInteres.getText());
					Cliente cli = controlador.buscarCliente(tipoCed, cedula);

					if (cli == null) {
						JOptionPane.showMessageDialog(null, "Este usuario no existe");
					} else {
						int numVer = controlador.CantidadPro(cli);
						boolean verificacionPro = controlador.verificarCantidadPro(cli);
						if (!verificacionPro) {
							JOptionPane.showMessageDialog(null, "Ya tiene 5 PRODUCTOS");
						} else {

							cuenta = new CuentaAhorros(numero, fechaexpedicion, cli, interes, saldo);

							controlador.crearCuentaAhorros(cuenta);
							JOptionPane.showMessageDialog(null, "Cuenta de ahorros creada y asignada a: "
									+ cli.getName() + " " + cli.getLastName());
							limpiarCamposProducto();
							limpiarTipoProducto();
						}
					}
				}
			} else {
				JOptionPane.showMessageDialog(null, "Seleccione tipo de producto");
			}
		} catch (ExcepcionNegocio e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}
		// GEN-FIRST:event_jBCrearProductoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBCrearProductoActionPerformed

	private void jBBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBBuscarProductoActionPerformed
		// TODO add your handling code here:
		try {
			String numero = JOptionPane.showInputDialog(null, "Por favor ingrese el numero de su tarjeta");
			if (numero.length() == 16) {
				TarjetaCredito tarj = controlador.buscarTarjeta(numero);
				if (tarj != null) {
					JOptionPane.showMessageDialog(null, "tarjeta encontrada");
					jCBTipoProducto.setSelectedIndex(2);
					jTFCvc.setText(tarj.getCvc());
					jTFNumeroPro.setText(tarj.getNumber());
					jDateFechaExpiracion.setDate(tarj.getExpirationDate());
					jCBFranquicia.setSelectedItem(tarj.getFranchise().getName());
					jTFIdCLienteProducto.setText(tarj.getCliente().getIdentificationNumber());
					jTFSaldo.setText(tarj.getAmmount() + "");
					jCBTipoId.setSelectedItem(tarj.getCliente().getIdentificationType());
				} else {
					JOptionPane.showMessageDialog(null, "NO EXISTE", "Error", JOptionPane.WARNING_MESSAGE);
				}

			} else if (numero.length() == 11) {
				CuentaAhorros cu = controlador.buscarCuentaAhorros(numero);
				if (cu != null) {
					JOptionPane.showMessageDialog(null, "cuenta de ahorros encontrada");
					jCBTipoProducto.setSelectedIndex(1);
					jTFNumeroPro.setText(cu.getNumber());
					jTFInteres.setText(cu.getSavingInterest() + "");
					jTFIdCLienteProducto.setText(cu.getCliente().getIdentificationNumber());
					jTFSaldo.setText(cu.getAmmount() + "");
					jCBTipoId.setSelectedItem(cu.getCliente().getIdentificationType());
				} else {
					JOptionPane.showMessageDialog(null, "NO EXISTE", "Error", JOptionPane.WARNING_MESSAGE);
				}

			} else {
				JOptionPane.showMessageDialog(null, "No existe un numero con esa cantidad de digitos");
			}

		} catch (NullPointerException nul) {
			JOptionPane.showMessageDialog(null, "Ingrese el numero a buscar", "Error en busqueda",
					JOptionPane.INFORMATION_MESSAGE);
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_jBBuscarProductoActionPerformed

	private void jBGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBGuardarClienteActionPerformed
		// TODO add your handling code here:
		try {
			if (jTFNombre.getText().isEmpty() || jTFApellido.getText().isEmpty() || jTFId.getText().isEmpty()
					|| jCBTipoId.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(null, "Diligencie todos los datos");
			} else {
				Cliente cli;

				String nombre = jTFNombre.getText();
				String id = jTFId.getText();
				TipoDocumento tipo = (TipoDocumento) jCBTipoId.getSelectedItem();
				String apellido = jTFApellido.getText();

				// cli.setName(jTFNombre.getText());
				// cli.setIdentificationType((String)jCBTipoId.getSelectedItem());
				// cli.setIdentificationNumber(jTFId.getText());
				// cli.setLastName(jTFApellido.getText());
				cli = new Cliente(nombre, apellido, tipo, id);

				controlador.crearCliente(cli);
				JOptionPane.showMessageDialog(null, "Cliente creado");
				limpiarCampos();
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_jBGuardarClienteActionPerformed

	private void jBBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBBuscarClienteActionPerformed
		// TODO add your handling code here:
		try {
			if (jTFId.getText().isEmpty() || jCBTipoId.getSelectedIndex() == 0) {
				JOptionPane.showMessageDialog(null, "Ingrese tipo y numero de documento a buscar");
			} else {
				Cliente cli = controlador.buscarCliente((TipoDocumento) jCBTipoId.getSelectedItem(), jTFId.getText());
				if (cli != null) {
					JOptionPane.showMessageDialog(null, "Cliente encontrado");
					jTFApellido.setText(cli.getLastName());
					jTFId.setText(cli.getIdentificationNumber());
					jTFNombre.setText(cli.getName());
					jCBTipoId.setSelectedItem(cli.getIdentificationType() + "");
				} else {
					JOptionPane.showMessageDialog(null, "NO EXISTE", "Error", JOptionPane.WARNING_MESSAGE);
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_jBBuscarClienteActionPerformed

	public void limpiarCamposTransaccion() {
		jTFCantidadTransaccion.setText("");
		jTFNumeroCuentaTransaccion.setText("");
		jCBTipoTransaccion.setSelectedIndex(0);
	}

	public void limpiarCampos() {
		jTFApellido.setText("");
		jTFNombre.setText("");
		jTFId.setText("");
		jCBTipoId.setSelectedIndex(0);
	}

	public void limpiarConsumo() {
		jCBTipoConsumo.setSelectedIndex(0);
		jTFValorTotalConsumo.setText("");
		jTFInteresConsumo.setText("");
		jCBCuotasConsumo.setSelectedIndex(0);
		jTFValorXPagarConsumo.setText("");
		jTFTarjetaCreditoConsumo.setText("");
	}

	public void limpiarPago() {
		jCBComoElPago.setSelectedIndex(0);
		jtfNumeroTCPago.setText("");
		jTFIngreseValorPago.setText("");
		jTFValorPagarPago.setText("");
		jTFAbonoCapital.setText("");
		jTFAbonoInteres.setText("");
	}

	public void limpiarCamposProducto() {
		jTFCvc.setText("");
		jTFInteres.setText("");
		jTFIdCLienteProducto.setText("");
		jTFNumeroPro.setText("");
		jCBFranquicia.setSelectedIndex(0);
		jCBIdClienteProducto.setSelectedIndex(0);
		jTFSaldo.setText("");

	}

	public void limpiarTipoProducto() {
		jCBTipoProducto.setSelectedIndex(0);
	}

	public void listarCombo(JComboBox combo) {
		List<Franquicia> fra = controlador.ListarFranquicia();
		combo.removeAllItems();
		combo.addItem("Seleccione una Categoria");
		for (int i = 0; i < fra.size(); i++) {
			combo.addItem(fra.get(i).getName());
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(BancoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(BancoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(BancoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(BancoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new BancoPrincipal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarCliente;
    private javax.swing.JButton jBBuscarProducto;
    private javax.swing.JButton jBCrearProducto;
    private javax.swing.JButton jBGenerarPago;
    private javax.swing.JButton jBGuardarCliente;
    private javax.swing.JButton jBGuardarConsumo;
    private javax.swing.JButton jBGuardarTransaccion;
    private javax.swing.JButton jBRealizarPago;
    private javax.swing.JComboBox jCBComoElPago;
    private javax.swing.JComboBox jCBCuotasConsumo;
    private javax.swing.JComboBox jCBFranquicia;
    private javax.swing.JComboBox jCBIdClienteProducto;
    private javax.swing.JComboBox jCBTipoConsumo;
    private javax.swing.JComboBox jCBTipoId;
    private javax.swing.JComboBox jCBTipoProducto;
    private javax.swing.JComboBox jCBTipoTransaccion;
    private com.toedter.calendar.JDateChooser jDateFechaExpiracion;
    private javax.swing.JLabel jInteresConsumo;
    private javax.swing.JLabel jLAbonoCapital;
    private javax.swing.JLabel jLAbonoInteres;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCantidadOperacion;
    private javax.swing.JLabel jLCvc;
    private javax.swing.JLabel jLFechaExpiracion;
    private javax.swing.JLabel jLFranquicia;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLIdClienteProducto;
    private javax.swing.JLabel jLIngreseValorPago;
    private javax.swing.JLabel jLInteres;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNumeroCuentaTransaccion;
    private javax.swing.JLabel jLNumeroCuentaTransaccionOrigen;
    private javax.swing.JLabel jLNumeroCuotasConsumo;
    private javax.swing.JLabel jLPag;
    private javax.swing.JLabel jLPagadoBoolean;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JLabel jLTarjetaCreditoConsumo;
    private javax.swing.JLabel jLTipo;
    private javax.swing.JLabel jLValorPagarPago;
    private javax.swing.JLabel jLValorPorPagarConsumo;
    private javax.swing.JLabel jLValorTotalConsumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPCliente;
    private javax.swing.JPanel jPConsumo;
    private javax.swing.JPanel jPOperacion;
    private javax.swing.JPanel jPProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFAbonoCapital;
    private javax.swing.JTextField jTFAbonoInteres;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFCantidadTransaccion;
    private javax.swing.JTextField jTFCvc;
    private javax.swing.JTextField jTFId;
    private javax.swing.JTextField jTFIdCLienteProducto;
    private javax.swing.JTextField jTFIngreseValorPago;
    private javax.swing.JTextField jTFInteres;
    private javax.swing.JTextField jTFInteresConsumo;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFNumeroCuentaOrigen;
    private javax.swing.JTextField jTFNumeroCuentaTransaccion;
    private javax.swing.JTextField jTFNumeroPro;
    private javax.swing.JTextField jTFSaldo;
    private javax.swing.JTextField jTFTarjetaCreditoConsumo;
    private javax.swing.JTextField jTFValorPagarPago;
    private javax.swing.JTextField jTFValorTotalConsumo;
    private javax.swing.JTextField jTFValorXPagarConsumo;
    private javax.swing.JTabbedPane jTPPrincipal;
    private javax.swing.JLabel jlTipoOperacion;
    private javax.swing.JTextField jtfNumeroTCPago;
    // End of variables declaration//GEN-END:variables
}
